// FastJsonDL — basic usage example
//
#include "../config.h" // includes EPD_WIDTH, EPD_HEIGHT
#include <stdio.h>
#include "FastEPD.h"
#include "FastJsonDL.h"
// FONT
#include "fast/ubuntu40.h"
// ---------------------------------------------------------------------------
// Example font stubs — replace with real font data generated by the
// FastEPD fontconvert tool (see FastEPD/fontconvert/README.md).
// ---------------------------------------------------------------------------
//extern const uint8_t ubuntu40[];   

// Font registry: maps JSON "font" field values to in-memory font data.
static const FastJsonDLFont fonts[] = {
    { "Ubuntu40", ubuntu40 },
};

// ---------------------------------------------------------------------------
// JSON layout
// ---------------------------------------------------------------------------
// ORDER matters: items are rendered top-to-bottom, just as they appear in the
// "items" array.  Drawing a black bar before the white text ensures the text
// is visible.
static const char LAYOUT_JSON[] = R"({
  "display_bpp": 4,
  "clear": true,
  "items": [
    {
      "type": "drawString",
      "font": "Ubuntu40",
      "string": "FastJsonDL",
      "x": 30,
      "y": 70,
      "c": 0
    },
    {
      "type": "loadG5Image",
      "data": ["0xbf","0xbb","0x5a","0x00","0x45","0x00","0x43","0x00","0xff","0xff","0x3b","0x33","0x1f","0x7e","0x78","0x82",
"0x2b","0xeb","0x5a","0x26","0x3a","0x5d","0x2f","0xf3","0x21","0x89","0x74","0xd2","0xe9","0xa5","0xed","0x2e",
"0x9f","0xd3","0x4b","0xc9","0x53","0x4b","0xab","0x69","0x74","0x9b","0x4b","0xa4","0xda","0x5e","0x9b","0xea",
"0xad","0xa4","0xd5","0x26","0xd2","0x1a","0x4c","0x56","0x9a","0xab","0xd2","0x6b","0x4d","0x55","0xaa","0x43",
"0x4b","0x55","0xa5","0x4b","0x55","0xa5","0xaa","0xea","0xd4","0x7f","0xc0"],
      "x": 30,
      "y": 330,
      "w": 90,
      "h": 69,
      "fg": 15,
      "bg": 0
    }
  ]
})";

// ---------------------------------------------------------------------------
// app_main
// ---------------------------------------------------------------------------

// Using heap-allocated pointers avoids a Store access fault on RISC-V targets
// (e.g. ESP32-C5) where constructing a large C++ object in BSS/static storage
// inside app_main() can crash inside bbepInitPanel().  This matches the
// lifecycle used in production C5 firmware.
static FASTEPD      *epaper = nullptr;
static FastJsonDL   *dl     = nullptr;

extern "C" void app_main(void)
{
    // Allocate the EPD driver on the heap.
    epaper = new FASTEPD();

    // Initialise the panel.  Replace BB_PANEL_M5PAPERS3 with the constant
    // that matches your hardware (see the BB_PANEL_* enum in FastEPD.h).
    int rc = epaper->initPanel(BB_PANEL_SENSORIA_C5);
    if (rc != BBEP_SUCCESS) {
        printf("EPD init failed (%d)\n", rc);
        return;
    }

    // Optional: override the active pixel area and apply mirror/rotation flags.
    // Remove or adjust for your panel dimensions and orientation.
    epaper->setPanelSize(EPD_WIDTH, EPD_HEIGHT, BB_PANEL_FLAG_MIRROR_X);

    // Optional: select the rendering bit-depth.
    //   BB_MODE_1BPP — 1-bit black/white (fastest update)
    //   BB_MODE_2BPP — 4 grey levels
    //   BB_MODE_4BPP — 16 grey levels (set "display_bpp": 4 in JSON too)
    epaper->setMode(BB_MODE_4BPP);

    // Build the renderer on the heap and register the font table.
    dl = new FastJsonDL(*epaper);
    dl->setFontRegistry(fonts, sizeof(fonts) / sizeof(fonts[0]));

    // Render the JSON layout.
    if (!dl->renderJsonString(LAYOUT_JSON)) {
        printf("FastJsonDL error: %s\n", dl->getLastError());
        return;
    }

    // Push the frame buffer to the physical display.
    epaper->fullUpdate();
}

